import { Space } from "../types"

const dir = "/spaces/living-room"

/**
 * The open-plan living room and study. Also the home page hero. Coordinates
 * measured on day.jpg; the dusk plates are pixel-aligned edits of it.
 */
export const livingRoom: Space = {
  slug: "living-room",
  name: "Living room",
  summary: "A desk by the window, a sideboard and a windowsill, from afternoon to dusk.",
  alt: "A light, calm living room and study furnished with LAYERD lamps, vases, planters and figurines",
  plate: { width: 4800, height: 2036 },
  plates: {
    day: { src: `${dir}/day.jpg`, blur: `${dir}/day-blur.jpg` },
    duskOff: { src: `${dir}/dusk-off.jpg` },
    duskLit: { src: `${dir}/dusk.jpg`, blur: `${dir}/dusk-blur.jpg` },
  },
  poster: "day",
  objects: [
    { handle: "the-wave-lamp", name: "The Wave Lamp", box: { x: 0.17, y: 0.47, w: 0.054, h: 0.165 } },
    { handle: "kumiko-design-desk-organiser", name: "Kumiko desk organiser", box: { x: 0.094, y: 0.595, w: 0.051, h: 0.094 } },
    { handle: "minimalist-table-lamp-ribs", name: "Ribs table lamp", box: { x: 0.389, y: 0.515, w: 0.038, h: 0.169 } },
    { handle: "the-halo-vase", name: "The Halo Vase", box: { x: 0.442, y: 0.42, w: 0.035, h: 0.262 } },
    { handle: "nobody-bloom", name: "Nobody, Bloom", box: { x: 0.477, y: 0.525, w: 0.038, h: 0.162 } },
    { handle: "the-kenso-planter", name: "The Kenso Planter", box: { x: 0.557, y: 0.25, w: 0.121, h: 0.303 } },
    { handle: "knitted-polarbear-figurine-key-tag", name: "Knitted Polar Bear", box: { x: 0.807, y: 0.607, w: 0.053, h: 0.136 } },
    { handle: "knitted-fox-knitted-figurine-key-tag", name: "Knitted Fox", box: { x: 0.852, y: 0.636, w: 0.043, h: 0.124 } },
  ],
  acts: [
    {
      id: "arrival",
      span: 1.1,
      stops: [0],
      layout: "hero",
      frame: { x: 0, y: 0, w: 1, h: 1 },
      fit: "cover",
      scene: "day",
      tone: "light",
      products: [],
      title: "Shape your space.",
      body: "Objects for the desk, the shelf and the windowsill. Designed and 3D printed in Sri Lanka, layer by layer.",
    },
    {
      id: "desk",
      span: 1.5,
      layout: "focus",
      frame: { x: 0.08, y: 0.44, w: 0.16, h: 0.27 },
      fit: "cover",
      scene: "day",
      tone: "light",
      products: ["the-wave-lamp", "kumiko-design-desk-organiser"],
      title: "A calmer desk.",
      body: "One lamp for the evenings, one organiser for everything else.",
    },
    {
      id: "living",
      span: 1.5,
      layout: "focus",
      frame: { x: 0.375, y: 0.24, w: 0.31, h: 0.47 },
      phoneFrame: { x: 0.38, y: 0.4, w: 0.15, h: 0.3 },
      fit: "cover",
      scene: "day",
      tone: "light",
      products: ["minimalist-table-lamp-ribs", "the-halo-vase", "nobody-bloom", "the-kenso-planter"],
      title: "A shelf with a point of view.",
      body: "Ribbed light, a black vessel, a quiet figure and a wall that grows.",
    },
    {
      id: "dusk",
      span: 2.4,
      hold: 0.78,
      // The room goes dark, then one nudge plays the lamps coming on in turn
      stops: [0.26, 0.74],
      layout: "caption",
      frame: { x: 0.06, y: 0.12, w: 0.66, h: 0.78 },
      fit: "cover",
      scene: "day",
      light: {
        fade: { to: "duskOff", from: 0, until: 0.22 },
        reveal: {
          plate: "duskLit",
          at: ["the-wave-lamp", "minimalist-table-lamp-ribs"],
          start: 0.28,
          step: 0.16,
          fill: [0.6, 0.72],
        },
      },
      tone: "dark",
      products: [],
      title: "Then the light goes.",
      body: "Every LAYERD lamp is printed in fine layers, so the light comes through the lines.",
    },
    {
      id: "gifts",
      span: 1.4,
      layout: "focus",
      frame: { x: 0.795, y: 0.58, w: 0.11, h: 0.2 },
      fit: "cover",
      scene: "duskLit",
      tone: "dark",
      products: ["knitted-polarbear-figurine-key-tag", "knitted-fox-knitted-figurine-key-tag"],
      title: "Small things, soft edges.",
      body: "Knitted Friends, as a figurine or a key tag.",
    },
    {
      id: "room",
      span: 1.3,
      stops: [0.2],
      layout: "end",
      frame: { x: 0, y: 0, w: 1, h: 1 },
      fit: "cover",
      scene: "duskLit",
      tone: "dark",
      products: [],
      title: "Your space, finished.",
      body: "Every piece in this room is in the shop. Tap one to see it up close.",
    },
  ],
}
